spring:
  jpa:
    database: mysql
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    properties:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/bill_service_db?serverTimezone=UTC
    username: hbstudent
    password: hbstudent
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  servlet:
    context-path: /bills
  port: 8082