spring:
  jpa:
    database: mysql
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    properties:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/deposit_service_db?serverTimezone=UTC
    username: hbstudent
    password: hbstudent
    driver-class-name: com.mysql.cj.jdbc.Driver

rabbitmq:
  port: 5672
  host: rabbitmq
  username: guest
  password: guest
  listener:
    direct:
      default-requeue-rejected: true